### ISSUE TITLE
lock file?

### ISSUE THREAD

**Issue by CodeL** [daxjuanxiong/infrared-small-target-detection#1]
Lock "wldmfunc.m?"

**Comment by daxjuanxiong** [comment]
> Lock "wldmfunc.m?"
添加好了

**Comment by CodeL** [comment]
感谢您的补充，我发现里面还缺少了这两个文件“dlcmfunc”“dgradfunc”，可否在您百忙之中补充一下呢？

**Comment by daxjuanxiong** [comment]
> 感谢您的补充，我发现里面还缺少了这两个文件“dlcmfunc”“dgradfunc”，可否在您百忙之中补充一下呢？

添加好了
